# Общие настройки для всех сервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud: INFO
    com.reactiverates: DEBUG

# Общие настройки JWT
jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey

# Общие настройки базы данных
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
