server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_rates_db
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: PT30M

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/reactive_rates_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/reactive_rates_db
    user: postgres
    password: postgres

# Настройки внешних API
exchangerate-api:
  base-url: https://v6.exchangerate-api.com
  api-key: feedc09fac544d8041317c40
  priority: 10
  timeout: 10s
  connect-timeout: 5s

unirate-api:
  base-url: https://api.unirateapi.com
  api-key: QashoCNTEdDqrEYt2WMMvUSMo3tyJz8BHpCXkqvSSgBUbqB5ruk7lu4HvwXbp3GV
  priority: 20
  timeout: 10s
  connect-timeout: 5s

mock-provider:
  enabled: false

cache:
  enabled: true
  ttl: PT5M
  max-size: 1000

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8081}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
